# .github/workflows/receiver.yml
name: Webhook Receiver

# This action is triggered by a "repository_dispatch" event
# We'll name our event 'notion-webhook'
on:
  repository_dispatch:
    types: [notion-webhook]

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code from the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Run our test script
      - name: Run Python Test Script
        # The GITHUB_EVENT_PATH is automatically available in this context
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: python main.py