# .github/workflows/scheduler.yml
name: Scheduled Test

on:
  schedule:
    # This runs every 5 minutes, the fastest allowed schedule.
    - cron: '*/5 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ping-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scheduled test script
        env:
          # Pull the secret URL into the environment
          CF_WORKER_URL: ${{ secrets.CF_WORKER_URL }}
        run: python scheduled_test.py